const state={fields:[['Organization / Authority',''],['Recruitment Name',''],['Advertisement No.',''],['Total Vacancy',''],['Application Start Date',''],['Last Date to Apply',''],['Exam Date',''],['Application Fee',''],['Minimum Age',''],['Maximum Age',''],['Age Relaxation',''],['Qualification / Eligibility',''],['Salary / Pay Scale',''],['Selection Process',''],['Job Location',''],['Application Mode',''],['How to Apply',''],['Documents Required','']],custom:[],tables:[],links:[],source:{pdf:'',url:''},rawText:'',status:'TEST'};
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderFields(){const box=$('fields');box.innerHTML=state.fields.map((f,i)=>`<div class="field-row"><label>${esc(f[0])}</label><input value="${esc(f[1])}" data-i="${i}"><button class="btn danger remove" onclick="removeField(${i})">×</button></div>`).join('');$('customFields').innerHTML=state.custom.map((f,i)=>`<div class="field-row"><input value="${esc(f[0])}" onchange="state.custom[${i}][0]=this.value"><textarea onchange="state.custom[${i}][1]=this.value">${esc(f[1])}</textarea><button class="btn danger remove" onclick="state.custom.splice(${i},1);renderFields()">×</button></div>`).join('')}
function syncFields(){document.querySelectorAll('#fields input').forEach(e=>state.fields[+e.dataset.i][1]=e.value)}
function addCustom(){state.custom.push(['New Field','']);renderFields()}; function removeField(i){state.fields.splice(i,1);renderFields()}
function addTable(){state.tables.push({name:'New Table',columns:['Column 1','Column 2'],rows:[['','']]});renderTables()}
function renderTables(){const box=$('tables');box.innerHTML=state.tables.map((t,ti)=>`<div class="card"><label>Table Name</label><input value="${esc(t.name)}" onchange="state.tables[${ti}].name=this.value"><div class="table-wrap"><table class="data-table"><thead><tr>${t.columns.map((c,ci)=>`<th><input value="${esc(c)}" onchange="state.tables[${ti}].columns[${ci}]=this.value"></th>`).join('')}<th>Action</th></tr></thead><tbody>${t.rows.map((r,ri)=>`<tr>${r.map((c,ci)=>`<td><input value="${esc(c)}" onchange="state.tables[${ti}].rows[${ri}][${ci}]=this.value"></td>`).join('')}<td><button class="btn danger" onclick="state.tables[${ti}].rows.splice(${ri},1);renderTables()">×</button></td></tr>`).join('')}</tbody></table></div><div class="row-actions"><button class="btn secondary" onclick="state.tables[${ti}].rows.push(Array(state.tables[${ti}].columns.length).fill(''));renderTables()">+ Row</button><button class="btn secondary" onclick="state.tables[${ti}].columns.push('New Column');state.tables[${ti}].rows.forEach(r=>r.push(''));renderTables()">+ Column</button><button class="btn danger" onclick="state.tables.splice(${ti},1);renderTables()">Delete Table</button></div></div>`).join('')}
function addLink(){state.links.push(['New Link','']);renderLinks()};function renderLinks(){$('links').innerHTML=state.links.map((l,i)=>`<div class="field-row"><input value="${esc(l[0])}" onchange="state.links[${i}][0]=this.value"><input value="${esc(l[1])}" onchange="state.links[${i}][1]=this.value"><button class="btn danger remove" onclick="state.links.splice(${i},1);renderLinks()">×</button></div>`).join('')}
function extractRegex(text,patterns){for(const p of patterns){const m=text.match(p);if(m&&m[1])return m[1].trim()}return ''}
function extractText(text){state.rawText=text;const rules={
'Organization / Authority':[/organization\s*[:\-]\s*([^\n]+)/i,/(?:commission|department|ministry)\s+of\s+([^\n]+)/i],
'Recruitment Name':[/recruitment\s*(?:name)?\s*[:\-]\s*([^\n]+)/i,/(.+?recruitment\s+20\d{2})/i],
'Advertisement No.':[/advertisement\s*(?:no|number)\.?\s*[:\-]?\s*([^\n|]+)/i,/(?:advt|advt\.\s*no\.?)\s*[:\-]?\s*([^\n|]+)/i],
'Total Vacancy':[/total\s+(?:vacancy|posts?)\s*[:\-]?\s*([\d,]+)/i,/(\d[\d,]+)\s+(?:posts?|vacancies)/i],
'Application Start Date':[/application\s+(?:begin|start|starts?)\s*[:\-]?\s*([^\n]+)/i,/(?:apply|application)\s+(?:from|start)\s*[:\-]?\s*([^\n]+)/i],
'Last Date to Apply':[/last\s+date(?:\s+to\s+apply)?\s*[:\-]?\s*([^\n]+)/i,/(?:apply|application)\s+(?:up to|till)\s*[:\-]?\s*([^\n]+)/i],
'Exam Date':[/exam\s+date\s*[:\-]?\s*([^\n]+)/i],
'Minimum Age':[/minimum\s+age\s*[:\-]?\s*([^\n]+)/i],
'Maximum Age':[/maximum\s+age\s*[:\-]?\s*([^\n]+)/i],
'Age Relaxation':[/age\s+relaxation\s*[:\-]?\s*([^\n]+)/i],
'Qualification / Eligibility':[/qualification\s*[:\-]\s*([\s\S]{1,500}?)(?:\n\s*age|\n\s*salary|\n\s*selection|$)/i,/(?:eligibility|educational qualification)\s*[:\-]\s*([\s\S]{1,500}?)(?:\n\s*age|\n\s*selection|$)/i],
'Salary / Pay Scale':[/pay\s*scale\s*[:\-]?\s*([^\n]+)/i,/(?:salary|stipend)\s*[:\-]?\s*([^\n]+)/i],
'Selection Process':[/selection\s+process\s*[:\-]?\s*([^\n]+)/i],
'Job Location':[/job\s+location\s*[:\-]?\s*([^\n]+)/i],
'Application Mode':[/application\s+mode\s*[:\-]?\s*([^\n]+)/i]
};state.fields.forEach(f=>{if(!f[1]&&rules[f[0]])f[1]=extractRegex(text,rules[f[0]])});const title=extractRegex(text,[/(.{0,80}recruitment.{0,80})/i]);if(title&&!state.fields[1][1])state.fields[1][1]=title;renderFields();checkData();preview()}
async function readPdf(file){$('extractStatus').innerHTML='<span class="pill">Reading PDF…</span>';try{if(!window.pdfjsLib)throw Error('PDF.js not loaded');const buf=await file.arrayBuffer(),pdf=await pdfjsLib.getDocument({data:buf}).promise;let out='';for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p);const c=await page.getTextContent();out+=c.items.map(x=>x.str).join(' ')+'\n'}if(out.replace(/\s/g,'').length<80){$('extractStatus').innerHTML='<span class="warn">⚠ PDF appears scanned/image-only. V1 cannot reliably OCR it yet; use manual fields or OCR in the next version.</span>';return} $('extractStatus').innerHTML='<span class="ok">✓ Text extracted from '+pdf.numPages+' page(s).</span>';extractText(out)}catch(e){$('extractStatus').innerHTML='<span class="bad">PDF read error: '+esc(e.message)+'</span>'}}
function checkData(){syncFields();const required=['Organization / Authority','Recruitment Name','Total Vacancy','Last Date to Apply'];let found=0,missing=[];state.fields.forEach(f=>{if(f[1])found++;if(required.includes(f[0])&&!f[1])missing.push(f[0])});const score=Math.round(found/state.fields.length*100);$('check').innerHTML=`<div class="check"><b>DATA CHECK</b><br>Fields found: ${found}/${state.fields.length} (${score}%)<br>${missing.length?'<span class="bad">❌ Required missing: '+missing.map(esc).join(', ')+'</span>':'<span class="ok">✓ Required core fields present.</span>'}<br><span class="muted">This is a V1 rule-based check, not proof of correctness.</span></div>`;return !missing.length}
function preview(){syncFields();const vals=state.fields.filter(f=>f[1]);$('preview').innerHTML=`<div class="preview-head"><span class="pill">TEST PREVIEW</span><h1>${esc(state.fields.find(f=>f[0]=='Recruitment Name')?.[1]||'Untitled Vacancy')}</h1><div>${esc(state.fields.find(f=>f[0]=='Organization / Authority')?.[1]||'')}</div></div>${section('Job Information',vals.slice(0,7))}${section('Application Fee',vals.filter(f=>f[0]=='Application Fee'))}${section('Age Limit',vals.filter(f=>/Age/.test(f[0])))}${section('Eligibility & Selection',vals.filter(f=>/Qualification|Selection|Salary/.test(f[0])))}${state.custom.filter(f=>f[1]).map(f=>section(f[0],[f])).join('')}${state.tables.map(t=>`<div class="section"><h3>${esc(t.name)}</h3><div class="table-wrap"><table class="data-table"><thead><tr>${t.columns.map(c=>`<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${t.rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`).join('')}${state.links.length?`<div class="section"><h3>Important Links</h3>${state.links.map(l=>`<p><a href="${esc(l[1])}" target="_blank">${esc(l[0])}</a></p>`).join('')}</div>`:''}`}
function section(title,arr){return !arr.length?'':`<div class="section"><h3>${esc(title)}</h3><div class="kv">${arr.map(f=>`<div><b>${esc(f[0])}</b><span>${esc(f[1])}</span></div>`).join('')}</div></div>`}
function execute(){if(!checkData()){alert('Required data missing. Please edit before Execute.');return}syncFields();state.status='EXECUTED_TEST';state.executedAt=new Date().toISOString();localStorage.setItem('onestopJobV1TestRecord',JSON.stringify(state));const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='onestop-job-test-record.json';a.click();$('executeStatus').innerHTML='<span class="ok">✓ Test execution complete. JSON snapshot saved locally. Nothing was published to the live website.</span>'}
$('pdf').addEventListener('change',e=>e.target.files[0]&&readPdf(e.target.files[0]));$('url').addEventListener('input',e=>state.source.url=e.target.value);$('checkBtn').onclick=checkData;$('previewBtn').onclick=preview;$('executeBtn').onclick=execute;renderFields();renderTables();renderLinks();
