/** Gaurav's World — Secure Admin Backend. Secrets only in Script Properties. */
const MAX_IMAGE_BYTES = 2 * 1024 * 1024;
function doGet(e){try{assertAdmin_();if(e&&e.parameter&&e.parameter.api==='1')return json_({ok:true,service:'gauravs-world-admin-api',version:5});return HtmlService.createHtmlOutputFromFile('Admin').setTitle("Gaurav's World — Secure Admin");}catch(err){return HtmlService.createHtmlOutput('<h2>Access denied</h2><p>'+escapeHtml_(safeMessage_(err))+'</p>');}}
function health(){assertAdmin_();const p=PropertiesService.getScriptProperties();return{ok:true,admin:Session.getActiveUser().getEmail(),githubConfigured:!!(p.getProperty('GITHUB_TOKEN')&&p.getProperty('GITHUB_OWNER')&&p.getProperty('GITHUB_REPO')),openaiConfigured:!!p.getProperty('OPENAI_API_KEY')};}
function listArticles(){assertAdmin_();try{const m=githubGetJson_('gauravs-world/data/articles.json');const a=Array.isArray(m)?m:(m.articles||[]);return{ok:true,articles:a.slice(0,500)};}catch(e){if(String(e.message).indexOf('HTTP 404')>=0)return{ok:true,articles:[]};throw e;}}
function getArticle(slug){assertAdmin_();const s=safeSlug_(slug);try{return{ok:true,article:githubGetJson_('gauravs-world/data/articles/'+s+'.json')}}catch(e){try{return{ok:true,article:githubGetJson_('gauravs-world/data/drafts/'+s+'.json'),draft:true}}catch(_){throw e;}}}
function saveDraft(input){assertAdmin_();const a=normalize_(input);a.status='draft';a.updatedAt=new Date().toISOString();const r=githubPutJson_('gauravs-world/data/drafts/'+a.slug+'.json',a,'Save Gaurav World draft: '+a.slug);return{ok:true,article:a,commit:r.commit};}
function publishArticle(input){assertAdmin_();const a=normalize_(input);a.status='published';const now=new Date().toISOString();a.publishedAt=a.publishedAt||now;a.updatedAt=now;const r=githubPutJson_('gauravs-world/data/articles/'+a.slug+'.json',a,'Publish Gaurav World article: '+a.slug);let entries=[];try{const m=githubGetJson_('gauravs-world/data/articles.json');entries=Array.isArray(m)?m:(m.articles||[])}catch(e){if(String(e.message).indexOf('HTTP 404')<0)throw e}entries=entries.filter(x=>x&&x.slug!==a.slug&&x.id!==a.slug);entries.unshift({id:a.slug,slug:a.slug,title:a.title,category:a.category,summary:a.summary,image:a.image,author:a.author,authorUrl:a.authorUrl,publishedAt:a.publishedAt,updatedAt:a.updatedAt});entries=entries.slice(0,500);const mr=githubPutJson_('gauravs-world/data/articles.json',{articles:entries,updatedAt:a.updatedAt},'Update Gaurav World manifest');try{githubDelete_('gauravs-world/data/drafts/'+a.slug+'.json','Remove published draft: '+a.slug)}catch(_){}return{ok:true,commit:mr.commit,url:'https://onestopfzd.in/gauravs-world/article-dynamic.html?id='+encodeURIComponent(a.slug)};}
function unpublishArticle(slug){assertAdmin_();const s=safeSlug_(slug);try{githubDelete_('gauravs-world/data/articles/'+s+'.json','Unpublish Gaurav World article: '+s)}catch(e){if(String(e.message).indexOf('HTTP 404')<0)throw e}let entries=[];try{const m=githubGetJson_('gauravs-world/data/articles.json');entries=Array.isArray(m)?m:(m.articles||[])}catch(e){if(String(e.message).indexOf('HTTP 404')<0)throw e}entries=entries.filter(x=>x&&x.slug!==s&&x.id!==s);const r=githubPutJson_('gauravs-world/data/articles.json',{articles:entries,updatedAt:new Date().toISOString()},'Remove article from Gaurav World manifest');return{ok:true,commit:r.commit};}
function deleteDraft(slug){assertAdmin_();const s=safeSlug_(slug);try{return githubDelete_('gauravs-world/data/drafts/'+s+'.json','Delete Gaurav World draft: '+s)}catch(e){if(String(e.message).indexOf('HTTP 404')>=0)return{ok:true};throw e;}}
function uploadImage(file){assertAdmin_();if(!file||typeof file!=='object')throw new Error('Invalid image');const name=String(file.name||'').trim(),mime=String(file.mime||'').toLowerCase(),b64=String(file.base64||'');if(!/^[A-Za-z0-9][A-Za-z0-9._-]{0,150}\.(png|jpe?g|webp)$/i.test(name))throw new Error('Use PNG, JPG, JPEG or WEBP filename');if(!/^image\/(png|jpeg|webp)$/.test(mime))throw new Error('Unsupported image type');if(!b64)throw new Error('Empty image');const bytes=Utilities.base64Decode(b64);if(bytes.length>MAX_IMAGE_BYTES)throw new Error('Image is larger than 2 MB');const r=githubPutBinary_('gauravs-world/images/'+name,bytes,'Upload Gaurav World cover: '+name);return{ok:true,path:'images/'+name,commit:r.commit};}
function generateDraft(input){assertAdmin_();const title=required_(input&&input.title,160,'title'),category=optional_(input.category,'Technology',80,'category'),notes=optional_(input.notes,'',5000,'notes');const p=PropertiesService.getScriptProperties(),key=p.getProperty('OPENAI_API_KEY');if(!key)throw new Error('OPENAI_API_KEY is not configured');const model=p.getProperty('OPENAI_MODEL')||'gpt-4.1-mini',payload={model,instructions:'Write an original factual Hindi-first blog article with useful English technical terms. Return JSON only with keys summary, bodyMarkdown, tags. Do not invent citations.',input:'Title: '+title+'\nCategory: '+category+'\nNotes: '+notes,text:{format:{type:'json_object'}}};const r=UrlFetchApp.fetch('https://api.openai.com/v1/responses',{method:'post',contentType:'application/json',headers:{Authorization:'Bearer '+key},payload:JSON.stringify(payload),muteHttpExceptions:true});if(r.getResponseCode()<200||r.getResponseCode()>=300)throw new Error('OpenAI request failed (HTTP '+r.getResponseCode()+')');const out=JSON.parse(r.getContentText()),d=JSON.parse(extractOutputText_(out));if(!d||typeof d.summary!=='string'||typeof d.bodyMarkdown!=='string')throw new Error('Invalid AI draft');return{ok:true,title,category,summary:d.summary.slice(0,1500),bodyMarkdown:d.bodyMarkdown.slice(0,30000),tags:Array.isArray(d.tags)?d.tags.slice(0,15).map(String):[]};}
function normalize_(i){if(!i||typeof i!=='object')throw new Error('Invalid article');const slug=safeSlug_(i.slug),title=required_(i.title,160,'title'),category=optional_(i.category,'Technology',80,'category'),summary=optional_(i.summary,'',1500,'summary'),body=required_(i.bodyMarkdown||i.body,30000,'body'),image=optional_(i.image,'',300,'image'),author=optional_(i.author,'Gaurav',100,'author'),authorUrl=optional_(i.authorUrl||i.authorURL,'https://onestopfzd.in/gauravs-world/author-gaurav.html',300,'authorUrl'),publishedAt=optional_(i.publishedAt,'',40,'publishedAt');if(image&&(!/^images\/[A-Za-z0-9][A-Za-z0-9._/-]*\.(png|jpe?g|webp)$/i.test(image)||image.indexOf('..')>=0))throw new Error('Invalid image path');return{id:slug,slug,title,category,summary,bodyMarkdown:body,image,author,authorUrl,tags:Array.isArray(i.tags)?i.tags.slice(0,15).map(x=>String(x).slice(0,60)):[],...(publishedAt?{publishedAt}: {})};}
function assertAdmin_(){const p=PropertiesService.getScriptProperties(),expected=String(p.getProperty('ADMIN_EMAIL')||'').trim().toLowerCase(),actual=String(Session.getActiveUser().getEmail()||'').trim().toLowerCase();if(!expected)throw new Error('Admin is not configured');if(!actual||actual!==expected)throw new Error('Unauthorized: sign in with the configured admin Google account');}
function safeSlug_(v){const s=required_(v,100,'slug').toLowerCase();if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(s))throw new Error('Invalid slug');return s;}
function required_(v,max,f){if(typeof v!=='string')throw new Error('Invalid '+f);const s=v.trim();if(!s||s.length>max)throw new Error('Invalid '+f+' length');return s;}
function optional_(v,fallback,max,f){if(v===undefined||v===null||v==='')return fallback;if(typeof v!=='string')throw new Error('Invalid '+f);const s=v.trim();if(s.length>max)throw new Error('Invalid '+f+' length');return s||fallback;}
function cfg_(){const p=PropertiesService.getScriptProperties(),token=p.getProperty('GITHUB_TOKEN'),owner=p.getProperty('GITHUB_OWNER'),repo=p.getProperty('GITHUB_REPO'),branch=p.getProperty('GITHUB_BRANCH')||'main';if(!token||!owner||!repo)throw new Error('GitHub backend is not configured');return{token,owner,repo,branch};}
function ghUrl_(path){const c=cfg_();return'https://api.github.com/repos/'+encodeURIComponent(c.owner)+'/'+encodeURIComponent(c.repo)+'/contents/'+path.split('/').map(encodeURIComponent).join('/');}
function ghHeaders_(){const c=cfg_();return{Authorization:'Bearer '+c.token,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'};}
function githubGetJson_(path){const c=cfg_(),r=UrlFetchApp.fetch(ghUrl_(path)+'?ref='+encodeURIComponent(c.branch),{headers:ghHeaders_(),muteHttpExceptions:true});if(r.getResponseCode()!==200)throw new Error('GitHub lookup failed (HTTP '+r.getResponseCode()+')');const f=JSON.parse(r.getContentText());return JSON.parse(Utilities.newBlob(Utilities.base64Decode(String(f.content).replace(/\n/g,''))).getDataAsString('UTF-8'));}
function existingSha_(path){const c=cfg_(),r=UrlFetchApp.fetch(ghUrl_(path)+'?ref='+encodeURIComponent(c.branch),{headers:ghHeaders_(),muteHttpExceptions:true});if(r.getResponseCode()===404)return null;if(r.getResponseCode()!==200)throw new Error('GitHub lookup failed (HTTP '+r.getResponseCode()+')');return JSON.parse(r.getContentText()).sha;}
function githubPutJson_(path,data,message){const c=cfg_(),payload={message,content:Utilities.base64Encode(JSON.stringify(data,null,2),Utilities.Charset.UTF_8),branch:c.branch},sha=existingSha_(path);if(sha)payload.sha=sha;const r=UrlFetchApp.fetch(ghUrl_(path),{method:'put',contentType:'application/json',headers:ghHeaders_(),payload:JSON.stringify(payload),muteHttpExceptions:true});if(r.getResponseCode()<200||r.getResponseCode()>=300)throw new Error('GitHub write failed (HTTP '+r.getResponseCode()+')');return{commit:JSON.parse(r.getContentText()).commit.sha};}
function githubPutBinary_(path,bytes,message){const c=cfg_(),payload={message,content:Utilities.base64Encode(bytes),branch:c.branch},sha=existingSha_(path);if(sha)payload.sha=sha;const r=UrlFetchApp.fetch(ghUrl_(path),{method:'put',contentType:'application/json',headers:ghHeaders_(),payload:JSON.stringify(payload),muteHttpExceptions:true});if(r.getResponseCode()<200||r.getResponseCode()>=300)throw new Error('GitHub image upload failed (HTTP '+r.getResponseCode()+')');return{commit:JSON.parse(r.getContentText()).commit.sha};}
function githubDelete_(path,message){const c=cfg_(),sha=existingSha_(path);if(!sha)throw new Error('HTTP 404: file not found');const r=UrlFetchApp.fetch(ghUrl_(path),{method:'delete',contentType:'application/json',headers:ghHeaders_(),payload:JSON.stringify({message,sha,branch:c.branch}),muteHttpExceptions:true});if(r.getResponseCode()<200||r.getResponseCode()>=300)throw new Error('GitHub delete failed (HTTP '+r.getResponseCode()+')');return{ok:true,commit:JSON.parse(r.getContentText()).commit.sha};}
function extractOutputText_(r){if(r&&typeof r.output_text==='string')return r.output_text;for(const o of (r&&r.output)||[])for(const c of (o.content||[]))if(c.type==='output_text'&&typeof c.text==='string')return c.text;throw new Error('No AI text output');}
function safeMessage_(e){const m=String(e&&e.message||'Request failed');if(/token|secret|api.?key|bearer/i.test(m))return'Request failed; check server configuration.';return m.slice(0,240);}
function escapeHtml_(s){return String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
function json_(v){return ContentService.createTextOutput(JSON.stringify(v)).setMimeType(ContentService.MimeType.JSON);}
