/* ONESTOP P2P WebRTC transport - website deployment. Documents are transferred over a WebRTC DataConnection; this app does not store document bytes on a server. */
(function(){
const PEERJS_URL='https://unpkg.com/peerjs@1.5.4/dist/peerjs.min.js';const CHUNK_SIZE=64*1024;const CONNECT_TIMEOUT=15000;let peerJsPromise=null;
function loadPeerJS(){if(window.Peer)return Promise.resolve(window.Peer);if(peerJsPromise)return peerJsPromise;peerJsPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=PEERJS_URL;s.async=true;s.onload=()=>window.Peer?resolve(window.Peer):reject(new Error('PeerJS loaded but Peer is unavailable'));s.onerror=()=>reject(new Error('Could not load the WebRTC connection service. Check internet access.'));document.head.appendChild(s);});return peerJsPromise;}
function errorText(e){return e?.message||e?.type||String(e||'Unknown error');}
window.createAdminPeer=async function(onConnection,onReady,onError){const Peer=await loadPeerJS();return new Promise((resolve,reject)=>{const peer=new Peer();let settled=false;const fail=e=>{const err=e instanceof Error?e:new Error(errorText(e));if(!settled){settled=true;reject(err);}onError&&onError(err);};peer.on('open',id=>{settled=true;onReady&&onReady(id);resolve(peer);});peer.on('connection',conn=>onConnection(conn));peer.on('error',fail);peer.on('disconnected',()=>onError&&onError(new Error('PeerJS disconnected from signaling service.')));peer.on('close',()=>onError&&onError(new Error('Admin receiver closed.')));setTimeout(()=>{if(!settled)fail(new Error('Admin receiver startup timed out.'));},CONNECT_TIMEOUT);});};
window.connectCustomer=async function(adminId,onConnected,onError){const id=String(adminId||'').trim();if(!id)throw new Error('Enter the Admin Connection ID first.');const Peer=await loadPeerJS();return new Promise((resolve,reject)=>{const peer=new Peer();let done=false;let timer=setTimeout(()=>fail(new Error('Connection timed out. Check the Admin ID and make sure the Admin page is open.')),CONNECT_TIMEOUT);const fail=e=>{if(done)return;done=true;clearTimeout(timer);try{peer.destroy();}catch(_){}const err=e instanceof Error?e:new Error(errorText(e));onError&&onError(err);reject(err);};peer.on('error',e=>fail(e));peer.on('open',()=>{const conn=peer.connect(id,{reliable:true,serialization:'binary'});conn.on('open',()=>{if(done)return;done=true;clearTimeout(timer);onConnected(conn,peer);resolve({conn,peer});});conn.on('error',e=>fail(e));});peer.on('disconnected',()=>fail(new Error('WebRTC signaling disconnected.')));});};
window.attachP2PReceiver=function(conn,onJob,onProgress,onState){let current=null;conn.on('data',async msg=>{try{if(msg&&msg.kind==='job-start'){current={meta:msg.meta,jobId:msg.jobId,files:[],file:null};onState&&onState('job-start');return;}if(msg&&msg.kind==='file-start'){if(!current)throw new Error('File arrived without a job.');current.file={name:msg.name,mime:msg.mime||'application/octet-stream',size:msg.size||0,received:0,chunks:[]};return;}if(msg&&msg.kind==='file-end'){if(!current?.file)throw new Error('File end received without a file.');const f=current.file;const blob=new Blob(f.chunks,{type:f.mime});if(f.size&&blob.size!==f.size)throw new Error(`File size mismatch for ${f.name}.`);current.files.push({name:f.name,mime:f.mime,size:blob.size,blob});current.file=null;if(current.meta?.fileCount&&current.files.length>=current.meta.fileCount){const job={jobId:current.jobId,meta:current.meta,files:current.files};onJob&&onJob(job);onState&&onState('job-received');current=null;}return;}if(msg instanceof ArrayBuffer||ArrayBuffer.isView(msg)){if(!current?.file)throw new Error('Binary chunk arrived without a file.');const chunk=msg instanceof ArrayBuffer?msg:msg.buffer.slice(msg.byteOffset,msg.byteOffset+msg.byteLength);current.file.chunks.push(chunk);current.file.received+=chunk.byteLength;onProgress&&onProgress(current.file,Math.min(1,current.file.received/Math.max(1,current.file.size)));}}catch(e){onState&&onState('error',e);}});conn.on('close',()=>onState&&onState('closed'));conn.on('error',e=>onState&&onState('error',e));};
async function sendBuffer(conn,buffer,onProgress,file){for(let offset=0;offset<buffer.byteLength;offset+=CHUNK_SIZE){const end=Math.min(offset+CHUNK_SIZE,buffer.byteLength);const chunk=buffer.slice(offset,end);await waitForBuffer(conn);conn.send(chunk);onProgress&&onProgress(file,Math.min(1,end/buffer.byteLength));}}function waitForBuffer(conn){return new Promise(resolve=>{const poll=()=>{if(!conn.open||((conn.dataChannel?.bufferedAmount||0)<1024*1024)){resolve();return;}setTimeout(poll,25);};poll();});}
window.sendP2PJob=async function(conn,files,meta,onProgress){if(!conn||!conn.open)throw new Error('Not connected to Admin.');if(!files?.length)throw new Error('Select at least one file.');const jobId='JOB-'+Date.now().toString(36).toUpperCase()+'-'+Math.random().toString(36).slice(2,7).toUpperCase();const cleanMeta={...meta,fileCount:files.length};conn.send({kind:'job-start',jobId,meta:cleanMeta});for(const file of files){const buffer=await file.arrayBuffer();conn.send({kind:'file-start',name:file.name,mime:file.type||'application/octet-stream',size:buffer.byteLength});await sendBuffer(conn,buffer,onProgress,file);conn.send({kind:'file-end'});}return jobId;};
window.sendP2PStatus=function(conn,jobId,status,message){try{if(conn?.open)conn.send({kind:'status',jobId,status,message:message||''});}catch(_){};};
window.attachCustomerStatus=function(conn){conn.on('data',msg=>{if(msg?.kind==='status'&&window.__onP2PStatus)window.__onP2PStatus(msg);});conn.on('close',()=>window.__onP2PStatus&&window.__onP2PStatus({status:'DISCONNECTED',message:'Admin connection closed.'}));conn.on('error',e=>window.__onP2PStatus&&window.__onP2PStatus({status:'ERROR',message:errorText(e)}));};
})();